env:
    browser: true
    jquery: true
extends: 'eslint:recommended'
parserOptions:
    ecmaFeatures:
            impliedStrict: true
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - off
    semi:
        - error
        - always
    no-console:
        - off
    no-unused-vars:
        - off
    no-undef:
        - off
    no-extra-boolean-cast:
        - off
