# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedTests',
            new_name='CompletedTest',
        ),
        migrations.RenameModel(
            old_name='ConfigTables',
            new_name='Config',
        ),
        migrations.RenameModel(
            old_name='CurrentController',
            new_name='CurrentTest',
        ),
        migrations.RenameModel(
            old_name='ConfigController',
            new_name='TestConfig',
        ),
    ]
