# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 16:58
from __future__ import unicode_literals

import checker.utils.model_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
        ('checker', '0002_auto_20160825_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='currenttest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='currenttest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 25, 14, 8, 42, 869532, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currenttest',
            name='updated',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 8, 25, 14, 8, 45, 925527, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkingprocedure',
            name='mac',
            field=checker.utils.model_fields.MacField(max_length=16),
        ),
        migrations.AlterField(
            model_name='checkingprocedure',
            name='status',
            field=checker.utils.model_fields.StatusField(),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.Config'),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='mac',
            field=checker.utils.model_fields.MacField(max_length=16),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currenttest',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker.Config'),
        ),
        migrations.AlterField(
            model_name='currenttest',
            name='mac',
            field=checker.utils.model_fields.MacField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='currenttest',
            name='status',
            field=checker.utils.model_fields.StatusField(),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='next_status',
            field=checker.utils.model_fields.StatusField(),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Request'),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.Response'),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='status',
            field=checker.utils.model_fields.StatusField(),
        ),
        migrations.CreateModel(
            name='FailResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checker.Response')),
                ('code', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=128)),
                ('http_status', models.PositiveSmallIntegerField()),
            ],
            bases=('checker.response',),
        ),
        migrations.CreateModel(
            name='SuccessResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checker.Response')),
                ('json_content', checker.utils.model_fields.JSONField()),
            ],
            bases=('checker.response',),
        ),
    ]
