# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 14:55
from __future__ import unicode_literals

import checker.utils.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20160825_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', checker.utils.model_fields.MacField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', checker.utils.model_fields.StatusField()),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.Config')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.Request')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.Response')),
            ],
        ),
        migrations.AddField(
            model_name='currenttest',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.Request'),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker.Request'),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker.Response'),
        ),
    ]
